version: '3'

services:
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
  phoenix:
    image: elixir:1.9-alpine
    environment:
      MIX_ENV: dev
    build:
      context: .
      args:
        - MIX_ENV=dev
    volumes:
      - .:/opt/app
      - mix_deps:/opt/app/deps
    command: mix phx.server
    ports:
      - "4000:4000"
    depends_on:
      - neo4j

volumes:
  mix_deps:
